spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/student_portal
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=8001



#MAIL SERVICE
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=gaurangsharma555@gmail.com
spring.mail.password=ypod hwcb aqwb sadw


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
